services:
- docker
script:
- docker build -t 7diracseas/jupyter .
deploy:
  provider: script
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" -e geoffrey@zombie.guru
    - docker push 7diracseas/jupyter:latest
  on:
    branch: master
env:
  global:
  - secure: sad3yvGs/nRc8QgeFmKWVQFaIIpSIz8DXwJBCkmxZXNz1qEq4Gip8sg2Oq3o1WlRc47PCRTq0aZ2ce0R1REvMGHQz3tviAQ65IYZfYtU7z5jEM3/HGzWl3/F5OWKZ/aiLiE/cgQ6oXTjEvjeOZp+109vV89lYF2gWH7MTHFJ7mXP9+OkshsCT6O5WhifJlX4FzbX+2WQ8upq17tCSbXY7DTZHLPzG1oecdNko35fCKhQgAVncz7UeHZ5Se5XgiTh7kESqyQrnYmdR3hdCvGyUNlDbyz3BhUxFXwkvcruCWc7nRqmh979v7h7kzxuDkT8FhLv/LflzUPeC4Z7dsRXMAo1Jwu5DZQTuJL+KpFTXyoGZnofMC9FoTNMSJIUb3mFcxkWkiLpoG5CN8faoJ3Xyk+XzQMtOCM1vDCXZ0Qzh+DimRe9sz13wvB3LLl55JmfqvOXihearbVulCe3Nl/ED7muiZs8BltMsmmJpm9zkiIDN6M/zGlGhKuJ5QD/3okcH9liA1g9BeK4JKXvtxArhh2n1QzsEhrPDZf88GyBnyVAEQGBS6deNeHMrr4utoVREG6pDSNTlC92kEKDBKUHMMPmIgqf3y2NVvXPRYLeez9myFl/zMO1dZMaEnXWWB8OEVF5kLL0RXFQValbCjWFY25tNbPfOtDOqSM8WMmMdF4=
  - secure: N+utFYXuVPHpnTuayFYh/LG4ZLzplT4aiJJpM9dSRz8zqKNBp2WrbciRy6E9/Ya6nP0MHhMZZv1GBf6xCJdAnno0RnN/JigHR7E83uHBsD4mQwsCQeYSGHKtzwCXoBzDztUvnT5+TIPh1Je/HplLUuMcTxbBzYrwdOKMMWUx4GQApDCn4ebGOe+hnBn+7N6BfuVvoILmyYOfm64CayDrxep6qOUPljyFh2JXxXMNRR0skQWqpLfdbKtKsEw3eODKkBO1i+eoAXfQmnC1EydHhYm/NVv6107Le0Rco4CteY9iM8E7+DVP26o6DgRQ3y83h8ntmougVBezPFrgTwP6gklQSNsvwBCC54hks2aifhCaNc4hvgO16O2qegKIAjpA1MGOnEMtFb3t4yM7b11uDoCtDFuKZpdAaSaQ2htuJ7ab+j1qPu36S6f7BoYuYpfDhJq5QFF/MyVItybTDyDBg9tab1zK5Ct3NbRS8J4jYQsy14hZ3l/7Y/mMWN1yyvUYBZDwN4Uy1AoY2tWKmrdqFMGS9MqsEN22Xhkryk2Ym+luohnlPZAYlGy/GFEvXDJeArWq7MEZnNFzrMUw2Gkgg2HjKPFG6howvjWd1xiL9PfPEdOAVHK0jKDoXalIjfCCmzmzErk9C9q+fYS5c8uLMiWgxocQx4w0Z8Cnu8iOTIY=
